id: P010380
initial_creation_type: ocr
source_metadata:
  id: bdr:W28738
  title: ངོར་ཨེ་ཝཾ་ཆོས་ལྡན་གྱི་ལོ་རྒྱུས་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ
  author: ''
  volumes:
    94234f173c0c4637b513e07d050ae3a2:
      image_group_id: I1GS53485
      title: ''
      volume_number: 1
      total_pages: 87
