id: P010380
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:46:51.653741
source_metadata:
  id: bdr:W28738
  title: ངོར་ཨེ་ཝཾ་ཆོས་ལྡན་གྱི་ལོ་རྒྱུས་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ
  author: ''
  volumes:
    94234f173c0c4637b513e07d050ae3a2:
      image_group_id: I1GS53485
      title: ''
      volume_number: 1
      total_pages: 87
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
